name: Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish project
      run: dotnet publish ACVPatcher/ACVPatcher.csproj -c Release --self-contained
