name: ACVPatcher Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.204
      - name: Restore dependencies
        run: dotnet restore
      - name: Set version
        if: ${{ github.event_name == 'release' }}
        run: '"${{ github.event.release.tag_name }}" | Out-File -NoNewline -FilePath ./VERSION'
      - name: Build ACVPatcher
        run: dotnet build -c Release
      - name: Publish ACVPatcher DLL
        run: dotnet publish acvpatcher.sln -c Release
      - name: Copy license
        run: cp LICENSE ACVPatcher/bin/Release/net8.0/publish/LICENSE.txt
      - name: Copy notice
        run: cp NOTICE ACVPatcher/bin/Release/net8.0//publish/NOTICE.txt
      - name: Artifact Upload DLL
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: DLL
          path: ACVPatcher/bin/Release/net8.0/publish/
      - name: Compress Release Artifact
        if: ${{ github.event_name == 'release' }}
        run: 'Compress-Archive ACVPatcher/bin/Release/net8.0/publish/* ./release.zip'
      - name: Create Release
        if: ${{ github.event_name == 'release' }}
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.tag_name }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        if: ${{ github.event_name == 'release' }}
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: DLL.zip
          asset_content_type: application/zip
